### ISSUE TITLE
indexOutofbounds

### ISSUE THREAD

**Issue by jasminezz** [adwiv/android-fat-aar#41]
def resname = (aarPath.split(exploded_aar_dir)[1]).replace('/', ':');
this line in the latest file "fat-aar.gradle"  has the error in windows system :"the indexOutofBounds"
Reason is aarPath in windows has backslash character  "\".
while , the version before October 14 is ok. Please check submit files on October 14, and find which file's change causes the error. 
Wait for your update, thks~

**Comment by adwiv** [comment]
Hi, Thanks for the report. I have pushed the proposed fix to a different branch. Can you please check by using 

apply from: 'https://raw.githubusercontent.com/adwiv/android-fat-aar/fix-issue-41/fat-aar.gradle'

and let me know if it fixes the issue so that I can merge it with the master branch.

Cheers.

**Comment by jasminezz** [comment]
Hi~
Thanks for your  reply.
The bug has fixed, wait for your merge.

**Comment by adwiv** [comment]
Thanks for the report. Fix branch merged with master.
