### ISSUE TITLE
Won´t merge consumerProguardFiles of libraries

### ISSUE THREAD

**Issue by Nachbar90** [adwiv/android-fat-aar#5]
I´m using proguard in my modules.

As my project is a library, I´m using

release {
            consumerProguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

But proguard configurations of my sub-modules are not included in the core library after compiling

**Comment by adwiv** [comment]
Thanks for the pull request :+1:  Looks good and have merged it.

I have one concern still and maybe you can clarify. This might correctly handle the case when minify if enabled. However if minify is not enabled, all those files should become the consumerProguardFiles instead and should be embedded in the aar file so that the application can use them. Not sure how to handle that although :) Maybe two tasks or adding to consumerProguardFiles or proguardFiles depending on whether or not the proguard task exists.  I don't use multiple proguard files, so can't test myself. 

Thanks.

**Comment by Nachbar90** [comment]
Hello,

if you don´t specify a consumerProguardFile, it wont even create a
proguard.txt inside the library. Therefore it´s not neccessary to check if
the user has specified one.
Minify enabled has nothing todo with the consumerProguard files. Consumer
Proguard files are packed in the aar file and executed where the library is
used :)


I´ve  created another pull request where I also check, if the file exists.


Thank you,

Best regards


2015-10-21 17:20 GMT+02:00 GoodBoy Adwiv <notifications@github.com>:

> Thanks for the pull request [image: :+1:] Looks good and have merged it.
>
> I have one concern still and maybe you can clarify. This might correctly
> handle the case when minify if enabled. However if minify is not enabled,
> all those files should become the consumerProguardFiles instead and should
> be embedded in the aar file so that the application can use them. Not sure
> how to handle that although :) Maybe two tasks or adding to
> consumerProguardFiles or proguardFiles depending on whether or not the
> proguard task exists. I don't use multiple proguard files, so can't test
> myself.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adwiv/android-fat-aar/issues/5#issuecomment-149929943>
> .
>



-- 
Best regards,

Marian Klühspies

**Comment by adwiv** [comment]
Hi,

I misunderstood how you are doing handling it.

I have merged the pull request.

Thanks a lot.

**Comment by suhasgawde10** [comment]
where i can store my consumerProguardFiles in diffrent location.

**Comment by adwiv** [comment]
Hi Suhas, Couldn't understand your problem. Can you please elaborate.

**Comment by suhasgawde10** [comment]
Actually i have created one library for my customer and that i have to give him by applying proguard so that the code will be obfuscate. But i have read in stack overflow that we can not apply proguard on library, once that library is used in any project, the proguard applied in that project will be applied to library also. But as i want to give that library to customer so they can not see my code. 
What you could suggest for this? Please help me out

**Comment by adwiv** [comment]
You can apply proguard on library without much problems. Ignore what you
read on stackoverflow.

**Comment by suhasgawde10** [comment]
actually i have already applied Proguard on My Library but problem is that when i use that aar library inside my demo application for testing, library functions are just get decompiled and shows all functionality when i click on any library function by holding ctrl key it decompile and show all functions details. any other way to protect my code.

**Comment by adwiv** [comment]
That is how java works. If you want harder to decompile use the paid
version of proguard - Dexguard. Or write the main logic in C/C++ and use
JNI.

**Comment by suhasgawde10** [comment]
Ok sir , Thanks for suggesting me 👍

**Comment by pinhassi** [comment]
The only thing that worked for me is to define both options in my library:

release {
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
consumerProguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}
